PATROL_MOVING_TO = "PATROL_MOVING_TO"
PATROL_ARRIVED = "PATROL_ARRIVED"

REQUEST_CALCULATE_POSITION = "REQUEST_CALCULATE_POSITION"
REQUEST_EMERGENCY_CALL = "REQUEST_EMERGENCY_CALL"

INFORM_BACK_TO_ROUTE = "INFORM_BACK_TO_ROUTE"
INFORM_ARRIVED = "INFORM_ARRIVED"
INFORM_MOVING_TO = "INFORM_MOVING_TO"
INFORM_EMERGENCY_DONE = "INFORM_EMERGENCY_DONE"
INFORM_BACK_IN_BASE = "INFORM_BACK_IN_BASE"

ACCEPT_PATROL = "ACCEPT_PATROL"
