name: Build Wheels

on:
  push:
    tags:
      - 'v*'

jobs:
  build_wheels:
    if: github.event.base_ref == 'refs/heads/deploy-offline/police-patrol'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: pip install build

      - name: Build wheel
        run: python -m build

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel
          path: dist/*.whl

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
